import React, { useEffect } from 'react'
import './PowerPlantPage.css'
import p1 from './p1.webp'
import p2 from './p2.webp'

function PowerPlantPage() {
    useEffect(() => {
        window.scrollTo({
            top: 0,
            behavior: "smooth"
        })
    }, [])
  return (
    <section className='metallicBarrierPage-section'>
      <div className="container">
        <div className="heading">
            <span><i class="ri-arrow-right-double-fill"></i>Power Plant & Solar Plant<i class="ri-arrow-left-double-line"></i></span>
        </div>
        <div className="main-container">
            <div className="img-parent">
                <div className="img">
                <img src={p1} alt="" />
                </div>
                <div className="img">
                <img src={p2} alt="" />
                </div>
            </div>
            <div className="product-detail">
                <p>Solar Power Plant in India generates Solar Power using Solar resources in India, an alternative energy sources generated by our efficient Solar power plant products – manufactured and constructed. TVZSTEC power plant installation capacity of up to 1 MW with less maintenance to run it. Our quality in maintenance and commissioning service are best in the industry.</p>
                <strong>Solar Power Plant India- Introduction </strong>
                <p>In order to secure and enduring lifestyle, reliable and environment friendly Electrical energy development projects are essential for our world.</p>
                <p>A successful Solar power generation plant’s important criteria is sun radiation, fortunately India has High sunny days, compared to the Asian countries India gets high sun radiation, India is the enrich place in the world to Build the Solar-PV based power plant.</p>
                <p>The main advantages of the solar energy is very simple in structural; no running parts no need much maintenance. One simple example for 1 MW power plant can maintain by one skilled man power. its generate electrical energy up to 25 years without any big maintenance. Solar power plants are not emit any type of hazardous things. If you calculate environmental safety and maintenance cost of traditional power plant, solar energy generation is very economical one in the world.</p>
                <p>Explore our other products Rooftop solar-easy to install in the roof top by saving area, UPS- very simple cost effective on SUPS systems work with regular grid connected electricity works with available energy radiation charge the batteries using panels. No grid electrical supply for battery charging. </p>
                {/* <p>For Any Inquiry Please <a target='_blank' href="https://api.whatsapp.com/send?phone=919813513375">Click Here</a></p> */}
            </div>
        </div>
      </div>
    </section>
  )
}

export default PowerPlantPage
